spring:
  datasource:
    url: jdbc:postgresql://localhost:${POSTGRES_PORT:5332}/${POSTGRES_DB:assessment_db}
    username: ${POSTGRES_USER:assessment}
    password: ${POSTGRES_PASSWORD:123}
    hikari:
      pool-name: auth-hikari
      maximum-pool-size: 10
      minimum-idle: 0
      idle-timeout: 600000
      max-lifetime: 1740000
      connection-timeout: 30000
      auto-commit: false

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 10m
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "backend-assessment::"

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    baseline-version: 0

security:
  password-config:
    algorithm: argon2
    salt-length: 16       # bytes
    hash-length: 32       # bytes
    parallelism: 1        # threads
    memory-kb: 65536      # KiB (64 MiB)
    iterations: 3
  jwt:
    access-ttl-seconds: 900
    hmac-secret-base64: "3bdEKdWevTkp/eWTNInJg02cK/QAXSVfuUcojgcxrHQ="

  swagger:
    enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.cache: DEBUG

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus

  endpoint:
    health:
      probes:
        enabled: true
      show-details: when_authorized

  metrics:
    tags:
      application: backend-assessment



